sudo: required
services:
  - docker

before_install:
  - docker build -t nabs2309/docker-react -f Dockerfile.dev .

script:
 - docker run nabs2309/docker-react echo built

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-251724116101"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
